// Generated by CoffeeScript 1.3.3
(function() {
  var classes;

  classes = require("classes");

  module.exports = {
    show: function(el) {
      classes(el).remove("hidden");
      return el;
    },
    hide: function() {
      classes(el).add("hidden");
      return el;
    },
    cloak: function() {
      classes(el).add("cloaked");
      return el;
    },
    uncloak: function() {
      classe(el).remove("cloaked");
      return el;
    }
  };

}).call(this);
